name: Build and Publish Documentation

on:
  - push
  - pull_request
  - workflow_dispatch
  - create

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Document which reference
      uses: rlespinasse/github-slug-action@v4
      run: echo "Running for ${{ github.ref_name }}
           Uses URL Reference ${{ env.GITHUB_REF_SLUG_URL }}"
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
        cache: 'pip'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r docs/requirements.txt
    - name: Update documentation markdown with spec json
      run: |
        python docs/document.py
    - name: Configure Git user
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
    - name: Build docs
      run: |
        git fetch origin gh-pages --depth=1
        mike deploy --push --rebase ${{ env.GITHUB_REF_SLUG_URL }}
        echo "Documentation available at: http://tides-transit.github.io/TIDES/${{ env.GITHUB_REF_SLUG_URL }}"