name: Validate Frictionless Data Package Schema for Spec

on:
  pull_request:
    branches:
      - main
    paths:
      - 'spec/tides.spec.json'

jobs:
  validate_data_package:
    name: Validate Frictionless Schemas
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Validate Data Package schema
        uses: docker://orrosenblatt/validate-json-action:latest
        env:
          INPUT_SCHEMA: spec/tides-data-package.json
          INPUT_JSONS: spec/tides.spec.json