name: Validate Frictionless Table Schemas for Spec

on:
  pull_request:
    branches:
      - main
    paths:
      - 'spec/*.schema.json'
      - '!spec/tides.spec.json'

jobs:
  validate_tables:
    name: Validate other schema
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Validate Table schema
        uses: GrantBirki/json-yaml-validate@v1.5.0
        with:
          json_schema: spec/table-schema.json
          base_dir: spec
          json_exclude_regex: .*\.spec\.json$
