name: Validate Frictionless Data Package Schema for Spec

on:
  pull_request:
    branches:
      - main
    paths:
      - 'spec/tides.spec.json'

jobs:
  validate_data_package:
    name: Validate Frictionless Schemas
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Validate Data Package schema
        uses: GrantBirki/json-yaml-validate@v1.5.0
        with:
          json_schema: spec/tides-data-package.json
          base_dir: spec
          json_exclude_regex: .*\.schema\.json$